In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/raw/cyberpunk2077_all_reviews.csv')

/tmp/ipykernel_86655/280197534.py:1: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/raw/cyberpunk2077_all_reviews.csv')

In [3]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [4]:
df.head()

,recommendationid,language,review,timestamp_created,timestamp_updated,voted_up,votes_up,votes_funny,weighted_vote_score,comment_count,...,created,playtime_at_review,updated,steamid,num_games_owned,num_reviews,playtime_forever,playtime_last_two_weeks,playtime_at_review.1,last_played
0,153486817,english,It's very fun. I don't usually like open world...,1702441215,1702441215,True,0,0,0.0,0,...,2023-12-13,NaN,2023-12-13,76561198019963558,0,8,2482.0,2482.0,2452,1.702444e+09
1,153486735,french,loved it before 2.0\n\n\n\n\ndon't like it any...,1702441087,1702441087,False,0,0,0.0,0,...,2023-12-13,NaN,2023-12-13,76561198834145680,0,4,3349.0,38.0,3349,1.702439e+09
2,153486615,schinese,真的值得体验一下,1702440867,1702440867,True,0,0,0.0,0,...,2023-12-13,NaN,2023-12-13,76561199492331874,0,1,2163.0,1222.0,2116,1.702444e+09
3,153486487,english,fun,1702440650,1702440650,True,0,0,0.0,0,...,2023-12-13,NaN,2023-12-13,76561199103884291,0,9,6634.0,441.0,6622,1.702441e+09
4,153486273,english,Fun game,1702440259,1702440259,True,0,0,0.0,0,...,2023-12-13,NaN,2023-12-13,76561198131623718,354,3,10328.0,3.0,10324,1.702440e+09

In [5]:
df.shape

(681884, 27)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 681884 entries, 0 to 681883
Data columns (total 27 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   recommendationid             681884 non-null  int64
 1   language                     681884 non-null  object
 2   review                       679819 non-null  object
 3   timestamp_created            681884 non-null  int64
 4   timestamp_updated            681884 non-null  int64
 5   voted_up                     681884 non-null  bool
 6   votes_up                     681884 non-null  int64
 7   votes_funny                  681884 non-null  int64
 8   weighted_vote_score          681884 non-null  float64
 9   comment_count                681884 non-null  int64
 10  steam_purchase               681884 non-null  bool
 11  received_for_free            681884 non-null  bool
 12  written_during_early_access  681884 non-null  bool
 13  hidden_in_steam_china        681884 non-null  bool
 14  steam_china_location         0 non-null       float64
 15  timestamp_dev_responded      117 non-null     float64
 16  developer_response           117 non-null     object
 17  created                      681884 non-null  object
 18  playtime_at_review           0 non-null       float64
 19  updated                      681884 non-null  object
 20  steamid                      681884 non-null  int64
 21  num_games_owned              681884 non-null  int64
 22  num_reviews                  681884 non-null  int64
 23  playtime_forever             681883 non-null  float64
 24  playtime_last_two_weeks      681883 non-null  float64
 25  playtime_at_review.1         681884 non-null  int64
 26  last_played                  681883 non-null  float64
dtypes: bool(5), float64(7), int64(10), object(5)
memory usage: 117.7+ MB

In [7]:
df.describe()

,recommendationid,timestamp_created,timestamp_updated,votes_up,votes_funny,weighted_vote_score,comment_count,steam_china_location,timestamp_dev_responded,playtime_at_review,steamid,num_games_owned,num_reviews,playtime_forever,playtime_last_two_weeks,playtime_at_review.1,last_played
count,6.818840e+05,6.818840e+05,6.818840e+05,681884.000000,681884.000000,681884.000000,681884.000000,0.0,1.170000e+02,0.0,6.818840e+05,681884.000000,681884.000000,6.818830e+05,681883.000000,681884.000000,6.818830e+05
mean,1.008113e+08,1.633055e+09,1.637102e+09,2.626121,0.654831,0.172101,0.091256,NaN,1.638542e+09,NaN,7.656120e+16,99.420869,12.776466,7.897341e+03,106.949623,3181.366536,1.678507e+09
std,2.374631e+07,3.228722e+07,3.361719e+07,82.375051,43.850230,0.244662,2.123582,NaN,7.030213e+06,NaN,4.029356e+08,286.744044,29.381006,1.431956e+04,502.925290,5655.057173,3.032054e+07
min,8.191890e+07,1.607559e+09,1.607559e+09,0.000000,0.000000,0.000000,0.000000,NaN,1.629470e+09,NaN,7.656120e+16,0.000000,1.000000,0.000000e+00,0.000000,5.000000,0.000000e+00
25%,8.234335e+07,1.607950e+09,1.608134e+09,0.000000,0.000000,0.000000,0.000000,NaN,1.631697e+09,NaN,7.656120e+16,0.000000,2.000000,2.924000e+03,0.000000,664.000000,1.665590e+09
50%,8.455271e+07,1.610461e+09,1.616827e+09,0.000000,0.000000,0.000000,0.000000,NaN,1.644956e+09,NaN,7.656120e+16,0.000000,6.000000,5.424000e+03,0.000000,1888.000000,1.695920e+09
75%,1.225150e+08,1.663630e+09,1.667615e+09,1.000000,0.000000,0.494037,0.000000,NaN,1.645091e+09,NaN,7.656120e+16,110.000000,14.000000,9.418500e+03,0.000000,3993.000000,1.699813e+09
max,1.534868e+08,1.702441e+09,1.702455e+09,20082.000000,19488.000000,0.993787,556.000000,NaN,1.645197e+09,NaN,7.656120e+16,30226.000000,3878.000000,1.560337e+06,20115.000000,831446.000000,1.702462e+09

In [8]:
df['language'].value_counts().head(20)

language
english      288943
schinese     179896
russian       62896
german        21026
brazilian     19598
polish        18928
koreana       18412
turkish       15996
spanish       13101
french        11752
tchinese       8371
italian        3200
ukrainian      2949
czech          2808
latam          2404
japanese       2191
thai           1938
swedish        1474
hungarian      1148
dutch          1076
Name: count, dtype: int64

In [9]:
df_eng = df[df['language'] == 'english'].copy()
df_eng.shape

(288943, 27)

In [10]:
df_eng['review'].isnull().sum()

np.int64(1006)

In [11]:
df_eng['review'].duplicated().sum()

np.int64(37609)

In [12]:
df_eng[df_eng["review"].duplicated(keep=False)][["recommendationid", "review"]].head(20)

     recommendationid                      review
3           153486487                         fun
4           153486273                    Fun game
5           153486133                   cyberpunk
40          153481512          The game is fixed.
42          153481397                        good
44          153481229                      i like
57          153479244                          :)
72          153477778                         fun
76          153477039                          \n
78          153476902                         fun
81          153476322                        peak
90          153475618                         yes
93          153475432                  great game
95          153474671               Amazing game.
102         153473595                      nice\n
118         153471151              excellent game
134         153468174                       yes\n
155         153465833  One of the best games ever
158         153465706                 hell yeah\n
166         153464882                          👍👍

In [13]:
df_clean = df_eng.copy()

In [14]:
df_clean.dropna(subset=['review'], inplace=True)

In [15]:
df_clean["review"].duplicated().sum()

np.int64(36604)

In [16]:
print(df_clean.shape)

(287937, 27)

In [17]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 287937 entries, 0 to 681883
Data columns (total 27 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   recommendationid             287937 non-null  int64
 1   language                     287937 non-null  object
 2   review                       287937 non-null  object
 3   timestamp_created            287937 non-null  int64
 4   timestamp_updated            287937 non-null  int64
 5   voted_up                     287937 non-null  bool
 6   votes_up                     287937 non-null  int64
 7   votes_funny                  287937 non-null  int64
 8   weighted_vote_score          287937 non-null  float64
 9   comment_count                287937 non-null  int64
 10  steam_purchase               287937 non-null  bool
 11  received_for_free            287937 non-null  bool
 12  written_during_early_access  287937 non-null  bool
 13  hidden_in_steam_china        287937 non-null  bool
 14  steam_china_location         0 non-null       float64
 15  timestamp_dev_responded      82 non-null      float64
 16  developer_response           82 non-null      object
 17  created                      287937 non-null  object
 18  playtime_at_review           0 non-null       float64
 19  updated                      287937 non-null  object
 20  steamid                      287937 non-null  int64
 21  num_games_owned              287937 non-null  int64
 22  num_reviews                  287937 non-null  int64
 23  playtime_forever             287936 non-null  float64
 24  playtime_last_two_weeks      287936 non-null  float64
 25  playtime_at_review.1         287937 non-null  int64
 26  last_played                  287936 non-null  float64
dtypes: bool(5), float64(7), int64(10), object(5)
memory usage: 51.9+ MB

In [18]:
df_clean.drop(
    columns=[
        "playtime_at_review",
        "steam_china_location",
        "developer_response",
        "timestamp_dev_responded"
    ],
    inplace=True
)

In [19]:
df_clean.rename(
    columns={"playtime_at_review.1": "playtime_at_review"},
    inplace=True
)

In [20]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 287937 entries, 0 to 681883
Data columns (total 23 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   recommendationid             287937 non-null  int64
 1   language                     287937 non-null  object
 2   review                       287937 non-null  object
 3   timestamp_created            287937 non-null  int64
 4   timestamp_updated            287937 non-null  int64
 5   voted_up                     287937 non-null  bool
 6   votes_up                     287937 non-null  int64
 7   votes_funny                  287937 non-null  int64
 8   weighted_vote_score          287937 non-null  float64
 9   comment_count                287937 non-null  int64
 10  steam_purchase               287937 non-null  bool
 11  received_for_free            287937 non-null  bool
 12  written_during_early_access  287937 non-null  bool
 13  hidden_in_steam_china        287937 non-null  bool
 14  created                      287937 non-null  object
 15  updated                      287937 non-null  object
 16  steamid                      287937 non-null  int64
 17  num_games_owned              287937 non-null  int64
 18  num_reviews                  287937 non-null  int64
 19  playtime_forever             287936 non-null  float64
 20  playtime_last_two_weeks      287936 non-null  float64
 21  playtime_at_review           287937 non-null  int64
 22  last_played                  287936 non-null  float64
dtypes: bool(5), float64(4), int64(10), object(4)
memory usage: 43.1+ MB

In [21]:
df_clean["voted_up"].value_counts()

voted_up
True     242154
False     45783
Name: count, dtype: int64

In [22]:
# Save the cleaned data to processed directory
import os
os.makedirs('../data/processed', exist_ok=True)
df_clean.to_csv('../data/processed/cleaned_reviews.csv', index=False)
print('Cleaned reviews saved successfully!')

Cleaned reviews saved successfully!